# DigitalOcean App Platform Specification
name: motion-index-web
region: nyc1

services:
  - name: web
    source_dir: /
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true
    
    build_command: yarn install --frozen-lockfile && yarn build
    run_command: node build
    
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    http_port: 5000
    
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      failure_threshold: 3
      success_threshold: 1
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: HOST
        value: "0.0.0.0"
      - key: PUBLIC_SUPABASE_URL
        value: ${PUBLIC_SUPABASE_URL}
        type: SECRET
      - key: PUBLIC_SUPABASE_ANON_KEY
        value: ${PUBLIC_SUPABASE_ANON_KEY}
        type: SECRET
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: ${SUPABASE_SERVICE_ROLE_KEY}
        type: SECRET
      - key: PUBLIC_API_URL
        value: ${PUBLIC_API_URL}
        type: SECRET

# Auto-scaling configuration
alerts:
  - rule: CPU_UTILIZATION
    value: 80
    operator: GREATER_THAN
    window: 5M
    disabled: false

# Custom domains (optional)
# domains:
#   - domain: yourdomain.com
#     type: PRIMARY
#   - domain: www.yourdomain.com
#     type: ALIAS